export enum HttpStatusCodes {
  OK = 'OK',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  ACCEPTED = 'ACCEPTED',
  CREATED = 'CREATED',
  NOT_MODIFIED = 'NOT_MODIFIED',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE'
}
